In [63]:
import pandas as pd

adult = pd.read_csv(r'.\datasets\chapter_5\adult.data', header=None, names = ['Age', 'Work-Class', 'fnlwgt', 'Education', 'Education-Num', 'Marital-Status', 'Occupation', 'Relationship', 'Race', 'Sex', 'Capital-gain', 'Capital-loss', 'Hours-per-week', 'Native-Country', 'Earnings-Raw'])

In [64]:
print(adult.head())
adult.dropna(how='all', inplace=True)
adult.columns

   Age         Work-Class  fnlwgt   Education  Education-Num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        Marital-Status          Occupation    Relationship    Race      Sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   Capital-gain  Capital-loss  Hours-per-week  Native-Country Earnings-Raw  
0          2174             0              40   United-States  

Index(['Age', 'Work-Class', 'fnlwgt', 'Education', 'Education-Num',
       'Marital-Status', 'Occupation', 'Relationship', 'Race', 'Sex',
       'Capital-gain', 'Capital-loss', 'Hours-per-week', 'Native-Country',
       'Earnings-Raw'],
      dtype='object')

In [65]:
adult['Hours-per-week'].describe()

count    32561.000000
mean        40.437456
std         12.347429
min          1.000000
25%         40.000000
50%         40.000000
75%         45.000000
max         99.000000
Name: Hours-per-week, dtype: float64

In [66]:
adult['Education-Num'].median()

10.0

In [67]:
adult['Work-Class'].unique()

array([' State-gov', ' Self-emp-not-inc', ' Private', ' Federal-gov',
       ' Local-gov', ' ?', ' Self-emp-inc', ' Without-pay',
       ' Never-worked'], dtype=object)

In [68]:
adult['LongHours'] = adult['Hours-per-week'] > 40

In [69]:
# Variance Threshold transformer in sklearn
import numpy as np

X = np.arange(30).reshape((10, 3))
print(X)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]


In [70]:
X[:, 1] = 1

In [71]:
from sklearn.feature_selection import VarianceThreshold
vt = VarianceThreshold()
Xt = vt.fit_transform(X)
print(Xt)
print(vt.variances_)

[[ 0  2]
 [ 3  5]
 [ 6  8]
 [ 9 11]
 [12 14]
 [15 17]
 [18 20]
 [21 23]
 [24 26]
 [27 29]]
[27.  0. 27.]


In [72]:
X = adult[['Age', 'Education-Num', 'Capital-gain', 'Capital-loss', 'Hours-per-week']].values
print(X)

[[   39    13  2174     0    40]
 [   50    13     0     0    13]
 [   38     9     0     0    40]
 ...
 [   58     9     0     0    40]
 [   22     9     0     0    20]
 [   52     9 15024     0    40]]


In [73]:
y = (adult['Earnings-Raw'] == ' > 50K').values
print(y)

[False False False ... False False False]


In [77]:
from sklearn.feature_selection import SelectKBest 
from sklearn.feature_selection import chi2 
transformer = SelectKBest(score_func=chi2, k=3)
Xt_chi2 = transformer.fit_transform(X, y)
print(transformer.scores_)
print(Xt_chi2)

[nan nan nan nan nan]


AttributeError: 'numpy.ndarray' object has no attribute 'scores_'